---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt: name=apt-transport-https state=present update_cache=yes

- name: Install dependencies
  apt: name=ca-certificates state=present update_cache=yes

- name: Install dependencies
  apt: name=curl state=present update_cache=yes

- name: Install dependencies
  apt: name=software-properties-common state=present update_cache=yes
- name: Install dependencies
  apt: name=gnupg-agent state=present update_cache=yes

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: Upgrade all apt packages
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: Install Python pip
  apt: name=python3-pip update_cache=true state=present force_apt_get=yes


- name: install docker-py
  pip: name=docker-py

- name: Install Docker
  apt: name=docker.io state=present update_cache=yes

- name: copy custom files
  copy: 
   src: trigger-job.sh
   dest: ./trigger-job.sh

- name: copy custom files
  copy: 
   src: trigger-job.groovy
   dest: ./trigger-job.groovy
  
- name: copy custom files
  copy: 
   src: sample-maven-job_config.xml
   dest: ./sample-maven-job_config.xml

- name: copy custom files
  copy: 
   src: install-plugins.sh
   dest: ./install-plugins.sh

- name: copy custom files
  copy: 
   src: executors.groovy
   dest: ./executors.groovy

- name: copy custom files
  copy: 
   src: default-user.groovy
   dest: ./default-user.groovy

- name: copy custom files
  copy: 
   src: credentials.xml
   dest: ./credentials.xml

- name: copy custom files
  copy: 
   src: create-freestyle.groovy
   dest: ./create-freestyle.groovy

- name: copy custom files
  copy: 
   src: create-credential.groovy
   dest: ./create-credential.groovy

- name: copy custom files
  copy: 
   src: Dockerfile
   dest: ./Dockerfile

- name: copy custom files
  copy: 
   src: config.xml
   dest: ./config.xml

- name: Build Docker image from Dockerfile
  docker_image:
            name: jenkins_custom
            source: build
            build:
              path: ./
#            state: present
#          dockerfile: Dockerfile
- name: Running the container
  docker_container:
            name: jenkins_ansi_anil
            image: jenkins_custom:latest
            ports:
                    - 8881:8080
- name: Check if container is running
  shell: docker ps
